'$schema' = 'https://starship.rs/config-schema.json'

scan_timeout = 1000 # 1 second
command_timeout = 5000 # 5 second
palette = 'catppuccin_macchiato'

[character]
success_symbol = '[✓](bold green)'
error_symbol = '[✗](bold red)'
vimcmd_symbol = '[⟶](bold purple)'

[directory]
read_only = ' 󰌾'
style = 'bold blue'
truncation_length = 2
truncate_to_repo = false
truncation_symbol = '../'

[cmd_duration]
format = 'took [$duration]($style)'
style = 'white'

[git_branch]
symbol = ' '

[git_status]
style = 'bold cyan'

[package]
disabled = true

[palettes.catppuccin_macchiato]
rosewater = '#f4dbd6'
flamingo = '#f0c6c6'
pink = '#f5bde6'
mauve = '#c6a0f6'
red = '#ed8796'
maroon = '#ee99a0'
peach = '#f5a97f'
yellow = '#eed49f'
green = '#a6da95'
teal = '#8bd5ca'
sky = '#91d7e3'
sapphire = '#7dc4e4'
blue = '#8aadf4'
lavender = '#b7bdf8'
text = '#cad3f5'
subtext1 = '#b8c0e0'
subtext0 = '#a5adcb'
overlay2 = '#939ab7'
overlay1 = '#8087a2'
overlay0 = '#6e738d'
surface2 = '#5b6078'
surface1 = '#494d64'
surface0 = '#363a4f'
base = '#24273a'
mantle = '#1e2030'
crust = '#181926'

[aws]
symbol = '  '

[bun]
symbol = ' '

[c]
symbol = ' '

[dart]
symbol = ' '

[docker_context]
symbol = ' '

[elixir]
symbol = ' '

[golang]
symbol = ' '

[hostname]
ssh_symbol = ' '

[java]
symbol = ' '

[kotlin]
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = '󰍛 '

[nodejs]
symbol = ' '
detect_files = ['package.json', '.node-version', '!bun.lockb']

[ocaml]
symbol = ' '

[php]
symbol = ' '

[python]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[swift]
symbol = ' '

[os.symbols]
Alpaquita = ' '
Alpine = ' '
AlmaLinux = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Kali = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
RockyLinux = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Void = ' '
Windows = '󰍲 '
