#!/bin/sh

# Vscode extensions
extensions=(
  "aaron-bond.better-comments"
  "amimaro.remix-run-snippets"
  "bierner.markdown-preview-github-styles"
  "bradlc.vscode-tailwindcss"
  "braydie.glob-new-file"
  "cardinal90.multi-cursor-case-preserve"
  "catppuccin.catppuccin-vsc"
  "catppuccin.catppuccin-vsc-icons"
  "christian-kohler.npm-intellisense"
  "christian-kohler.path-intellisense"
  "circlecodesolution.ccs-flutter-color"
  "codezombiech.gitignore"
  "csstools.postcss"
  "dart-code.flutter"
  "dbaeumer.vscode-eslint"
  "donjayamanne.githistory"
  "drcika.apc-extension"
  "duniul.git-stage"
  "eamodio.gitlens"
  "editorconfig.editorconfig"
  "github.copilot"
  "github.copilot-chat"
  "github.vscode-github-actions"
  "github.vscode-pull-request-github"
  "humao.rest-client"
  "ionutvmi.path-autocomplete"
  "irongeek.vscode-env"
  "jkjustjoshing.vscode-text-pastry"
  "meganrogge.template-string-converter"
  "mhutchie.git-graph"
  "miguelsolorio.fluent-icons"
  "miguelsolorio.symbols"
  "mousavian.ssh-config-syntax-highlighter"
  "ms-dotnettools.csdevkit"
  "ms-dotnettools.csharp"
  "ms-dotnettools.vscode-dotnet-runtime"
  "ms-vscode.vscode-typescript-next"
  "naumovs.color-highlight"
  "pnp.polacode"
  "prisma.prisma"
  "sidneys1.gitconfig"
  "sleistner.vscode-fileutils"
  "standard.vscode-standard"
  "streetsidesoftware.code-spell-checker"
  "streetsidesoftware.code-spell-checker-portuguese-brazilian"
  "styled-components.vscode-styled-components"
  "tamasfe.even-better-toml"
  "tyriar.sort-lines"
  "usernamehw.errorlens"
  "vincaslt.highlight-matching-tag"
  "visualstudioexptteam.intellicode-api-usage-examples"
  "visualstudioexptteam.vscodeintellicode"
  "vue.volar"
  "wakatime.vscode-wakatime"
  "wallabyjs.console-ninja"
  "wmaurer.change-case"
  "yoavbls.pretty-ts-errors"
  "zhuangtongfa.material-theme"
)

for extension in "${extensions[@]}"; do
  msg_install "Installing $extension"
  code --install-extension $extension
  msg_ok "$extension installed"
done
