#!/bin/sh

code --install-extension aaron-bond.better-comments
code --install-extension amimaro.remix-run-snippets
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bradlc.vscode-tailwindcss
code --install-extension braydie.glob-new-file
code --install-extension cardinal90.multi-cursor-case-preserve
code --install-extension catppuccin.catppuccin-vsc
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension circlecodesolution.ccs-flutter-color
code --install-extension codezombiech.gitignore
code --install-extension codium.codium
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension drcika.apc-extension
code --install-extension duniul.git-stage
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension usernamehw.errorlens
code --install-extension github.copilot
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension humao.rest-client
code --install-extension ionutvmi.path-autocomplete
code --install-extension irongeek.vscode-env
code --install-extension jkjustjoshing.vscode-text-pastry
code --install-extension meganrogge.template-string-converter
code --install-extension mhutchie.git-graph
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.symbols
code --install-extension mousavian.ssh-config-syntax-highlighter
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension naumovs.color-highlight
code --install-extension pnp.polacode
code --install-extension prisma.prisma
code --install-extension sidneys1.gitconfig
code --install-extension sleistner.vscode-fileutils
code --install-extension standard.vscode-standard
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese-brazilian
code --install-extension styled-components.vscode-styled-components
code --install-extension tamasfe.even-better-toml
code --install-extension tyriar.sort-lines
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension vincaslt.highlight-matching-tag
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension wakatime.vscode-wakatime
code --install-extension wallabyjs.console-ninja
code --install-extension wmaurer.change-case
code --install-extension yoavbls.pretty-ts-errors
code --install-extension zhuangtongfa.material-theme
